[project]
name = "bitcoin-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi-cli>=0.0.20",
    "fastapi[standard]>=0.128.0",
    "sqlmodel>=0.0.31",
]
